Since you're working with what looks like synchronous code, async functions can use try...catch to handle any errors. 

try...catch is the most common way to handle exceptions when using async/await.